apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app1
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app1
spec:
  source:
    git:
      url: https://github.com/sample-accelerators/tanzu-java-web-app1
      ref:
        branch: main